### ISSUE TITLE
Expresividad

### ISSUE THREAD

**Issue by josibuttazzoni** [tomi-iglesias/pdp-2020#11]
https://github.com/tomi-iglesias/pdp-2020/blob/e3426a3698e5cf595fb016ea98c9e09d9ba22681/tp3.hs#L35

Pensá siempre qué es lo que hace la función. Acá le estas agregando una parte al nombre más que cambiándolo; de hecho el parámetro `nuevoNombre` no sería realmente el nuevo nombre, entendes? Me pongo demasiado gede igual con esto, pero tratá de ser lo más expresivo que puedas con los nombres

**Comment by tomi-iglesias** [comment]
Joya josi, gracias!
