### ISSUE TITLE
¿Como la podrías mejorar?

### ISSUE THREAD

**Issue by josibuttazzoni** [tomi-iglesias/pdp-2020#4]
https://github.com/tomi-iglesias/pdp-2020/blob/78e56f5305c27d23daf74f3d1d31d15a7e7e2533/tp3.hs#L49
https://github.com/tomi-iglesias/pdp-2020/blob/78e56f5305c27d23daf74f3d1d31d15a7e7e2533/tp3.hs#L50

Fijate que podes evitar la lógica repetida usando la función que te dije en #1 . Notá que el dinero de los participantes se modifica muchas veces a lo largo del ejercicio y cada vez que lo haces se repite la forma

**Comment by tomi-iglesias** [comment]
Corregido en issue 1
